.TH "Nodo" 3 "Version 0.0.7" "ProyectoCredito" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nodo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Nodo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNodo\fP (T valor)"
.br
.ti -1c
.RI "void \fBsetDato\fP (T valor)"
.br
.ti -1c
.RI "void \fBsetSiguiente\fP (\fBNodo\fP< T > *siguienteNodo)"
.br
.ti -1c
.RI "void \fBsetAnterior\fP (\fBNodo\fP< T > *anteriorNodo)"
.br
.ti -1c
.RI "T \fBgetDato\fP ()"
.br
.ti -1c
.RI "\fBNodo\fP< T > * \fBgetSiguiente\fP ()"
.br
.ti -1c
.RI "\fBNodo\fP< T > * \fBgetAnterior\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Project Untitled 
.PP
Definition at line \fB9\fP of file \fBNodo\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "void Nodo::Nodo (T valor)"

.PP
\fBParameters\fP
.RS 4
\fIvalor\fP 
.RE
.PP
Project Untitled \fBNodo\fP implementation 
.PP
\fBParameters\fP
.RS 4
\fIvalor\fP 
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBNodo\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBNodo\fP< T > * Nodo::getAnterior ()"

.PP
\fBReturns\fP
.RS 4
Nodo<T>* 
.RE
.PP

.PP
Definition at line \fB58\fP of file \fBNodo\&.cpp\fP\&.
.SS "T Nodo::getDato ()"

.PP
\fBReturns\fP
.RS 4
T 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBNodo\&.cpp\fP\&.
.SS "\fBNodo\fP< T > * Nodo::getSiguiente ()"

.PP
\fBReturns\fP
.RS 4
Nodo<T>* 
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBNodo\&.cpp\fP\&.
.SS "void Nodo::setAnterior (\fBNodo\fP< T > * anteriorNodo)"

.PP
\fBParameters\fP
.RS 4
\fIanteriorNodo\fP 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBNodo\&.cpp\fP\&.
.SS "void Nodo::setDato (T valor)"

.PP
\fBParameters\fP
.RS 4
\fIvalor\fP 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBNodo\&.cpp\fP\&.
.SS "void Nodo::setSiguiente (\fBNodo\fP< T > * siguienteNodo)"

.PP
\fBParameters\fP
.RS 4
\fIsiguienteNodo\fP 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBNodo\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoCredito from the source code\&.
